### ISSUE TITLE
Pressing ESC without buying anything keeps me in the menu forever

### ISSUE THREAD

**Issue by 12Echo** [daccakareem/qb-policegarage#1]
Hey, when I just press "ESC" without buying a car, it just has my camera floating forever without taking me out of the menu.

Gives this in the console:

script:policegarage 2131 (@policegarage/ui/main.js:5)

Don't really understand what it means in main.js, just says     
if(data.action == true){
        console.log('2131')

Edit: It's also starting to give me:

SCRIPT ERROR: @policegarage/cl_garage.lua:14: attempt to index a nil value (field 'job')

**Comment by daccakareem** [comment]
2131 is a print form the js script

make sure the name of the file is qb-policegarage to make the ui work

**Comment by daccakareem** [comment]
❤
